### PR TITLE
Boot upgrade + Code refactor

### PR DESCRIPTION
**Pull request by hamedmirzaei**
Spring boot version has been updated to _2.1.5.RELEASE_ and the code has been cleaned using [Lombok](_https://projectlombok.org/_) library. In addition, code style has been refactored using Intelij Idea itself.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hamedmirzaei Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-batch-processing&pullRequestId=32)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-batch-processing&pullRequestId=32) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hamedmirzaei Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-batch-processing&pullRequestId=32)!

**Comment by hamedmirzaei** [comment]
It seems that travis-ci has some problems with lombok library and is unable to find  getters, setters and etc.

**Comment by gregturn** [comment]
@hamedmirzaei I think we are going to pass on this. While useful, many users get befuddled by Lombok, and we don't want that in an introductory guide.

**Pull request closed without merging**
